### PR TITLE
Handle max comparisons properly when diff comparisons are present, fi…

### PR DESCRIPTION
**Pull request by kartiksubbarao**
…xes tommyod/paretoset#18

### CODE REVIEW

**Comment by kartiksubbarao** [comment]
Heh, I just added those spaces to make the numbers line up visually. I didn't realize Python CI would mark that as a problem :-)

**Comment by tommyod** [comment]
Hi! Thanks for the PR. :+1:  Could you push a few more commits to the branch?

To clean  up the formatting, install black and run it:
```
$ pip install black
$ black . -l 120 # Run this in the root directly of the project
```

Could you add a regression test for the example you included in the issue? e.g. add:
```python
    def test_max_and_diff_working_together(self):
        """Regression test for:
            https://github.com/tommyod/paretoset/issues/18
        """
        mask = paretoset([[2,0], 
                          [1,0], 
                          [0,1]], sense=['max', 'diff'])
        assert np.all(mask == np.array([True,  False,  True]))
```
to the class `TestParetoSetAPI` in the `test_api.py` file, for instance.

**Comment by kartiksubbarao** [comment]
I have made the requested updates. I'm not sure where the Contributing section is, feel free to add me to the list of contributors. Thanks for all of your work on this module, it has been very helpful for me!

**Comment by tommyod** [comment]
Thanks a lot. Great work!

**Pull request merged**
